/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org;

import org.controllers.ConnectionController;
import org.database.Database;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.sql.Connection;
import java.sql.SQLException;

public class AppTest {

    private static final String URL = "jdbc:h2:~/test;AUTO_SERVER=TRUE;Mode=MySQL";
    public static Connection connection;

    @Before
    public void init() throws SQLException {
        connection = ConnectionController.getNewConnection(URL);
    }

    @After
    public void close() throws SQLException {
        connection.close();
    }

    @Test
    public void shouldCreateStatement() throws SQLException {
        Database database = new Database(connection, "Products");
    }
}
